### ISSUE TITLE
Crash at the start

### ISSUE THREAD

**Issue by Bardsd** [Chase-san/TiTsEd#94]
Whenever i start the program it gets minimized and then a windows error pops ups after closing it the program closes as well,

**Comment by algoRhythm99** [comment]
What error message?

**Comment by ViDori** [comment]
Okay... Im having a similar issue, but in my case, it doesnt give me an error, it just closes whenever I try to get it to open a file... It just closes without any reason given.

**Comment by algoRhythm99** [comment]
A specific save or any save?
If specific, please attach or link.

**Comment by ViDori** [comment]
It is not a specific save, as far as I can tell. The problem is, whenever it tries to open (clicks "Open" for the drop down menu to appear) anything, it stops, thinks for a second (loading ring) and then closes. No error code is given or anything. It cant even get the drop down menu from the open menu to display. (Sorry for the late response)

**Comment by algoRhythm99** [comment]
So its crashing when enumerating the saves on your machine.
What do you usually use to play the game with, browser, flash player projector, air?

**Comment by algoRhythm99** [comment]
Can you try this version:
https://github.com/Chase-san/TiTsEd/releases/tag/v0.30.4

**Comment by ViDori** [comment]
Attempted it. Still did not work. I use Adobe Flash Player 32.0 r0 to play. Also, just to make sure we're on the same page, the screenshot bellow has the icon circled that causes the program to crash.
![tempsnip](https://user-images.githubusercontent.com/55543119/65427850-7b1dd700-ddd0-11e9-8148-f3c1d019de47.png)

**Comment by algoRhythm99** [comment]
Updated the https://github.com/Chase-san/TiTsEd/releases/tag/v0.30.4
Added some catches for generic exceptions and general code cleanup.
Can you try this version?

**Comment by ViDori** [comment]
Hey, you're trying to help me, who am I to tell you no? Unfortunately, still the same problem occurs.... Must have royally screwed up my computer to some degree...

**Comment by algoRhythm99** [comment]
Updated the https://github.com/Chase-san/TiTsEd/releases/tag/v0.30.4 again.
Can you try this?
There should be a TiTsEd.log next to the exe.
Can you link that?

**Comment by ViDori** [comment]
So, a few days ago, it started working again. I didnt say anything because I was afraid of it being a fluke, but the variant you gave me before the most recent one is now working.
I used the event logger in Windows to figure out what was causing the error. It listed some error with ".NET" something. So I used another program to repair it. Since then, the editor has been working... Dont know why though...
